Repository KTB-Sixmen/gitfolio_cloud, pull requests merged in 2024-12, with the labels that each got.

#26 21 [CLOUD] 쿠버네티스 클러스터 구축
  Ansible/ansible.cfg
  Ansible/instances.json
  Ansible/k8s.yaml
  Ansible/master.yaml
  Terraform/AWS/.terraform.lock.hcl
  Terraform/AWS/data.tf
  Terraform/AWS/module.tf
  Terraform/AWS/module/AMI/data.tf
  Terraform/AWS/module/AMI/output.tf
  Terraform/AWS/module/AZ/data.tf
  Terraform/AWS/module/AZ/output.tf
  Terraform/AWS/module/DB/NoSQL/output.tf
  Terraform/AWS/module/DB/NoSQL/resource.tf
  Terraform/AWS/module/DB/NoSQL/variables.tf
  Terraform/AWS/module/DB/RDS/resource.tf
  Terraform/AWS/module/DB/RDS/variable.tf
  Terraform/AWS/module/ECR/resource.tf
  Terraform/AWS/module/ECR/variable.tf
  Terraform/AWS/module/LB/alb.tf
  Terraform/AWS/module/LB/bot.tf
  Terraform/AWS/module/LB/data.tf
  Terraform/AWS/module/LB/front_dev.tf
  Terraform/AWS/module/LB/k8s.tf
  Terraform/AWS/module/LB/output.tf
  Terraform/AWS/module/LB/variable.tf
  Terraform/AWS/module/LB/web.tf
  Terraform/AWS/module/Route53/data.tf
  Terraform/AWS/module/Route53/resource.tf
  Terraform/AWS/module/Route53/variable.tf
  Terraform/AWS/module/network/output.tf
  Terraform/AWS/module/network/resource.tf
  Terraform/AWS/module/network/variable.tf
  Terraform/AWS/module/node/ai/output.tf
  Terraform/AWS/module/node/ai/resource.tf
  Terraform/AWS/module/node/ai/variable.tf
  Terraform/AWS/module/node/back/output.tf
  Terraform/AWS/module/node/back/resource.tf
  Terraform/AWS/module/node/back/variable.tf
  Terraform/AWS/module/node/cicd/resource.tf
  Terraform/AWS/module/node/cicd/variable.tf
  Terraform/AWS/module/node/front/output.tf
  Terraform/AWS/module/node/front/resource.tf
  Terraform/AWS/module/node/front/variable.tf
  Terraform/AWS/module/node/kubernetes/output.tf
  Terraform/AWS/module/node/kubernetes/resource.tf
  Terraform/AWS/module/node/kubernetes/variable.tf
  Terraform/AWS/output.tf
  Terraform/AWS/provider.tf
  Terraform/AWS/terraform.tf
  Terraform/AWS/variable.tf
  Terraform/Kubernetes/provier.tf
  Terraform/Kubernetes/terraform.tf
Labels: duplicate

#27 [CLOUD] 쿠버네티스 클러스터 구축
  Terraform/.terraform.lock.hcl
  Terraform/Kubernetes/provier.tf
  Terraform/Kubernetes/terraform.tf
  Terraform/data.tf
  Terraform/module.tf
  Terraform/module/AMI/data.tf
  Terraform/module/AMI/output.tf
  Terraform/module/AZ/data.tf
  Terraform/module/AZ/output.tf
  Terraform/module/DB/NoSQL/output.tf
  Terraform/module/DB/NoSQL/resource.tf
  Terraform/module/DB/NoSQL/variables.tf
  Terraform/module/DB/RDS/resource.tf
  Terraform/module/DB/RDS/variable.tf
  Terraform/module/ECR/resource.tf
  Terraform/module/ECR/variable.tf
  Terraform/module/LB/alb.tf
  Terraform/module/LB/bot.tf
  Terraform/module/LB/data.tf
  Terraform/module/LB/front_dev.tf
  Terraform/module/LB/k8s.tf
  Terraform/module/LB/output.tf
  Terraform/module/LB/variable.tf
  Terraform/module/LB/web.tf
  Terraform/module/Route53/data.tf
  Terraform/module/Route53/resource.tf
  Terraform/module/Route53/variable.tf
  Terraform/module/network/output.tf
  Terraform/module/network/resource.tf
  Terraform/module/network/variable.tf
  Terraform/module/node/ai/output.tf
  Terraform/module/node/ai/resource.tf
  Terraform/module/node/ai/variable.tf
  Terraform/module/node/back/output.tf
  Terraform/module/node/back/resource.tf
  Terraform/module/node/back/variable.tf
  Terraform/module/node/cicd/resource.tf
  Terraform/module/node/cicd/variable.tf
  Terraform/module/node/front/output.tf
  Terraform/module/node/front/resource.tf
  Terraform/module/node/front/variable.tf
  Terraform/module/node/kubernetes/output.tf
  Terraform/module/node/kubernetes/resource.tf
  Terraform/module/node/kubernetes/variable.tf
  Terraform/output.tf
  Terraform/provider.tf
  Terraform/terraform.tf
  Terraform/variable.tf
Labels: enhancement

#29 [CLOUD] 쿠버네티스 클러스터 구축
  Ansible/dock.yaml
  Terraform/module/DB/NoSQL/resource.tf
  Terraform/module/node/ai/resource.tf
  Terraform/module/node/front/resource.tf
  Terraform/terraform.tf
  kubernetes/backend/services/auth-service.yaml
  kubernetes/backend/services/member-service.yaml
  kubernetes/backend/services/notification-service.yaml
  kubernetes/backend/services/payment-service.yaml
  kubernetes/backend/services/resume-service.yaml
  kubernetes/base/ai/ai-configmap.yaml
  kubernetes/base/ai/ai-deployment.yaml
  kubernetes/base/ai/ai-service.yaml
  kubernetes/base/ai/backend-configmap.yaml
  kubernetes/base/backend/auth/auth-deployment.yaml
  kubernetes/base/backend/auth/auth-service.yaml
  kubernetes/base/backend/backend-configmap.yaml
  kubernetes/base/backend/chat/chat-deployment.yaml
  kubernetes/base/backend/chat/chat-service.yaml
  kubernetes/base/backend/frontend-configmap.yaml
  kubernetes/base/backend/kafka/kafka-deployment.yaml
  kubernetes/base/backend/kafka/kakfa-service.yaml
  kubernetes/base/backend/member/member-deployment.yaml
  kubernetes/base/backend/member/member-service.yaml
  kubernetes/base/backend/notification/notification-deployment.yaml
  kubernetes/base/backend/notification/notification-service.yaml
  kubernetes/base/backend/payment/payment-deployment.yaml
  kubernetes/base/backend/payment/payment-service.yaml
  kubernetes/base/backend/resume/resume-deployment.yaml
  kubernetes/base/backend/resume/resume-service.yaml
  kubernetes/base/backend/zookeeper/zookeeper-service.yaml
  kubernetes/base/configmap.yaml
  kubernetes/base/databases/mongo/mongodb-deployment.yaml
  kubernetes/base/databases/mongo/mongodb-pv.yaml
  kubernetes/base/databases/mongo/mongodb-pvc.yaml
  kubernetes/base/databases/mongo/mongodb-service.yaml
  kubernetes/base/databases/redis/redis-deployment.yaml
  kubernetes/base/databases/redis/redis-pv.yaml
  kubernetes/base/databases/redis/redis-pvc.yaml
  kubernetes/base/databases/redis/redis-service.yaml
  kubernetes/base/frontend/backend-configmap.yaml
  kubernetes/base/frontend/frontend-deployment.yaml
  kubernetes/base/frontend/frontend-service.yaml
  kubernetes/base/ingress/backend-ingress.yaml
  kubernetes/base/ingress/ingress-service.yaml
  kubernetes/base/ingress/ingress.yaml
  kubernetes/base/kustomization.yaml
  kubernetes/frontend/frontend-service.yaml
  kubernetes/overlays/dev/kustomization.yaml
  kubernetes/overlays/prod/kustomization.yaml
Labels: enhancement

#30 [CLOUD] 쿠버네티스 클러스터 구축(리소스)
  kubernetes/ai/ai-configmap.yaml
  kubernetes/ai/ai-deployment.yaml
  kubernetes/ai/ai-service.yaml
  kubernetes/ai/backend-configmap.yaml
  kubernetes/backend/auth/auth-deployment.yaml
  kubernetes/backend/auth/auth-service.yaml
  kubernetes/backend/backend-configmap.yaml
  kubernetes/backend/chat/chat-deployment.yaml
  kubernetes/backend/chat/chat-service.yaml
  kubernetes/backend/frontend-configmap.yaml
  kubernetes/backend/kafka/kafka-deployment.yaml
  kubernetes/backend/kafka/kakfa-service.yaml
  kubernetes/backend/member/member-deployment.yaml
  kubernetes/backend/member/member-service.yaml
  kubernetes/backend/notification/notification-deployment.yaml
  kubernetes/backend/notification/notification-service.yaml
  kubernetes/backend/payment/payment-deployment.yaml
  kubernetes/backend/payment/payment-service.yaml
  kubernetes/backend/resume/resume-deployment.yaml
  kubernetes/backend/resume/resume-service.yaml
  kubernetes/backend/zookeeper/zookeeper-service.yaml
  kubernetes/base/kustomization.yaml
  kubernetes/configmap.yaml
  kubernetes/databases/mongo/mongodb-deployment.yaml
  kubernetes/databases/mongo/mongodb-pv.yaml
  kubernetes/databases/mongo/mongodb-pvc.yaml
  kubernetes/databases/mongo/mongodb-service.yaml
  kubernetes/databases/redis/redis-deployment.yaml
  kubernetes/databases/redis/redis-pv.yaml
  kubernetes/databases/redis/redis-pvc.yaml
  kubernetes/databases/redis/redis-service.yaml
  kubernetes/frontend/backend-configmap.yaml
  kubernetes/frontend/frontend-deployment.yaml
  kubernetes/frontend/frontend-service.yaml
  kubernetes/ingress/backend-ingress.yaml
  kubernetes/ingress/ingress-service.yaml
  kubernetes/ingress/ingress.yaml
  kubernetes/overlays/dev/kustomization.yaml
  kubernetes/overlays/prod/kustomization.yaml
Labels: enhancement

#31 [CLOUD] Route53 분리
  Terraform/module/LB/alb.tf
  Terraform/module/LB/bot.tf
  Terraform/module/LB/front_dev.tf
  Terraform/module/LB/k8s.tf
  Terraform/module/LB/web.tf
  Terraform/module/Route53/resource.tf
  Terraform/module/node/ai/resource.tf
  Terraform/module/node/front/resource.tf
Labels: enhancement

#32 [CLOUD] 결제 모듈용 리스너 규칙 추가
  Terraform/module/LB/front_dev.tf
Labels: enhancement

#35 [RE] fix: 로드밸런서 resume, ai 규칙 수정
  Terraform/module/LB/front_dev.tf
  Terraform/module/node/cicd/resource.tf
Labels: bug

#36 feat: 젠킨스 관련 리소스 추가
  Ansible/cicd.yaml
  Ansible/instances.json
  Terraform/module.tf
  Terraform/module/Route53/resource.tf
  Terraform/module/network/resource.tf
  Terraform/module/node/cicd/output.tf
  Terraform/module/node/cicd/resource.tf
  Terraform/module/node/cicd/variable.tf
Labels: enhancement

#37 [CLOUD] 쿠버네티스 클러스터 리소스 검토 중
  Ansible/cicd.yaml
  Ansible/db.yaml
  Ansible/db_master.yaml
  Ansible/db_mongo.yaml
  Ansible/db_redis.yaml
  Ansible/db_slave.yaml
  Ansible/init_dev.yaml
  Ansible/instances.json
  Ansible/templates/docker-compose.db.yaml.j2
  Terraform/module.tf
  Terraform/module/AMI/data.tf
  Terraform/module/DB/NoSQL/resource.tf
  Terraform/module/DB/RDS/resource.tf
  Terraform/module/DB/RDS/variable.tf
  Terraform/module/network/output.tf
  Terraform/module/network/resource.tf
  Terraform/module/node/kubernetes/resource.tf
  Terraform/variable.tf
  kubernetes/ai/ai-configmap.yaml
  kubernetes/ai/ai-deployment.yaml
  kubernetes/ai/ai-service.yaml
  kubernetes/ai/backend-configmap.yaml
  kubernetes/backend/auth/auth-deployment.yaml
  kubernetes/backend/backend-configmap.dev.yaml
  kubernetes/backend/backend-configmap.yaml
  kubernetes/backend/chat/chat-deployment.yaml
  kubernetes/backend/chat/chat-service.yaml
  kubernetes/backend/frontend-configmap.yaml
  kubernetes/backend/member/member-deployment.yaml
  kubernetes/backend/notification/notification-deployment.yaml
  kubernetes/backend/payment/payment-deployment.yaml
  kubernetes/backend/resume/resume-deployment.yaml
  kubernetes/backend/zookeeper/zookeeper-deployment.yaml
  kubernetes/databases/mongo/mongodb-deployment.yaml
  kubernetes/databases/mongo/mongodb-pv.yaml
  kubernetes/databases/mongo/mongodb-pvc.yaml
  kubernetes/databases/mongo/mongodb-service.yaml
  kubernetes/databases/mongo/mongodb-statefulset.yaml
  kubernetes/databases/redis/redis-deployment.yaml
  kubernetes/databases/redis/redis-pv.yaml
  kubernetes/databases/redis/redis-pvc.yaml
  kubernetes/databases/redis/redis-service.yaml
  kubernetes/databases/redis/redis-statefulset.yaml
  kubernetes/frontend/frontend-configmap.yaml
  kubernetes/frontend/frontend-deployment.yaml
  kubernetes/ingress/backend-ingress.yaml
  kubernetes/ingress/ingress.yaml
Labels: enhancement

#38 feat : 젠킨스-깃허브 웹훅 연결을 위한 라우팅 설정 추가 (/jenkins/*)
  Terraform/module.tf
  Terraform/module/LB/alb.tf
  Terraform/module/LB/jenkins.tf
  Terraform/module/LB/variable.tf
  Terraform/module/node/cicd/jenkins-init.sh
  Terraform/module/node/cicd/output.tf
Labels: enhancement

#39 fix : 도커컴포즈 ecr 에 맞게 수정
  Ansible/argocd.yaml
  Ansible/instances.json
  Docker/back/docker-compose.back.yaml
  Terraform/output.tf
Labels: enhancement

#42 [CLOUD] 쿠버네티스 클러스터 구축
  Ansible/dock.yaml
  Ansible/instances.json
  Ansible/k8s_init.yaml
  Ansible/k8s_worker.yaml
  Ansible/templates/docker-compose.back.yaml.j2
  Ansible/templates/docker-compose.front.yaml.j2
  Ansible/templates/docker-compose.notification.yaml.j2
  Ansible/templates/docker-compose.yaml.j2
  Terraform/module.prod.tf
  Terraform/module.shared.tf
  Terraform/module/LB/prod/prod.tf
  Terraform/module/Route53/resource.tf
  kubernetes/ai/ai-configmap.yaml
  kubernetes/ai/ai-deployment.yaml
  kubernetes/ai/ai-service.yaml
  kubernetes/backend/backend-configmap.dev.yaml
  kubernetes/backend/backend-configmap.yaml
  kubernetes/backend/deployment/apply.sh
  kubernetes/backend/deployment/auth-deployment.yaml
  kubernetes/backend/deployment/chat-deployment.yaml
  kubernetes/backend/deployment/delete.sh
  kubernetes/backend/deployment/kafka-deployment.yaml
  kubernetes/backend/deployment/member-deployment.yaml
  kubernetes/backend/deployment/notification-deployment.yaml
  kubernetes/backend/deployment/payment-deployment.yaml
  kubernetes/backend/deployment/resume-deployment.yaml
  kubernetes/backend/deployment/zookeeper-deployment.yaml
  kubernetes/backend/service/auth-service.yaml
  kubernetes/backend/service/chat-service.yaml
  kubernetes/backend/service/kafka-service.yaml
  kubernetes/backend/service/member-service.yaml
  kubernetes/backend/service/notification-service.yaml
  kubernetes/backend/service/payment-service.yaml
  kubernetes/backend/service/resume-service.yaml
  kubernetes/backend/service/service.sh
  kubernetes/backend/service/zookeeper-service.yaml
  kubernetes/databases/mongo/mongodb-service.yaml
  kubernetes/databases/mongo/mongodb-values.yaml
  kubernetes/databases/redis/redis-service.yaml
  kubernetes/frontend/front-configmap.yaml
  kubernetes/frontend/front-deployment.yaml
  kubernetes/frontend/front-service.yaml
  kubernetes/ingress/ingress-service.yaml
  kubernetes/ingress/ingress-values.yaml
  kubernetes/ingress/ingress.yaml
  kubernetes/label.sh
  kubernetes/metrics/metrics-storageclass.yaml
  kubernetes/metrics/metrics-values.yaml
Labels: bug, enhancement
